### PR TITLE
Transitional Syntax (Port)

### PR DESCRIPTION
**Pull request by Bara20**
With this pull request is sm_hosties now incompatible with sm1.6 and lower.

**It's incompatible with #54**

### CODE REVIEW

**Comment by Bara20** [comment]
Compile works fine without warnings and errors (with sm1.9

**Comment by Bara20** [comment]
Now it works with sm1.7 and sm1.8 compiler.

ConVars in a new pull request?

**Comment by data-bomb** [comment]
Addresses Issue #56

**Comment by data-bomb** [comment]
Is Bara20:newSyntax a clone from master or beta branch?

**Comment by Bara20** [comment]
Beta

**Comment by Bara20** [comment]
Conflicts fixed with latest commits on beta branch.

**Comment by data-bomb** [comment]
This PR target can't change?  Try re-submitting against Beta branch. Still shows as Master

**Comment by Bara20** [comment]
base changed to beta

**Pull request merged**
