### PR TITLE
add chinese translate

### PR DESCRIPTION
**Pull request by owwo**

### CODE REVIEW

**Comment by dataviruset** [comment]
Hi, thanks for your contribution! It would be great if you could remove all "#format" lines from the translation file, it should only exist in one of the phrases files. Thanks! :)

**Comment by owwo** [comment]
I deleted.

**Comment by dataviruset** [comment]
Will merge this. Let me know if you are close to Beijing some day and I will buy you a coffee since I currently live here :)

**Comment by owwo** [comment]
In Beijing! Do you travel to Beijing? 
But I'm not here, I'm in Xian.

**Comment by dataviruset** [comment]
I live and work here. :)

**Pull request merged**
