### PR TITLE
Use ClientCommand for First/Third Person in csgo

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by data-bomb** [comment]
How does this method work?  Aren't these cheat commands?

**Comment by Bara20** [comment]
Yes, but it works fine with ClientCommand.

**Comment by data-bomb** [comment]
I'm worried this is not so efficient with OnPreThink.  What about if we start/stop the SDKHook only when we need it?  e.g., when the SetFirstPerson/SetThirdPerson are called?  As a consequence we would need to bring them back into the fold of lastrequest.sp and deprecate them in the lastrequest.inc

**Comment by Bara20** [comment]
Hm, I'll take a look tomorrow or this weekend.

**Comment by Bara20** [comment]
It will only called in ThirdPerson KnifeFight.

**Comment by data-bomb** [comment]
@Bara20 The SetFirstPerson/SetThirdPerson in the INC file can't be changed this way because external plugins won't be able to give the input as the game type as-written.

**Comment by data-bomb** [comment]
https://github.com/dataviruset/sm-hosties/commit/5b14bb008f98ec73f69eff08b786858c4e42dd18 and https://github.com/dataviruset/sm-hosties/commit/efff7c6e9014add3f1109dba065c255b8c166803 supersede this due to above comments.

**Pull request closed without merging**
