### PR TITLE
Fixed Compilation warnings

### PR DESCRIPTION
**Pull request by owwo**

### CODE REVIEW

**Comment by Bara20** [comment]
Already done with #9

**Comment by owwo** [comment]
Why, I will "sm_hosties_announce_wpn_attack" set to enabled, but announce is in console?

**Comment by Bara20** [comment]
Because "sm_hosties_announce_attack"
> Enable or disable announcements when a CT attacks a non-rebelling T: 0 - disable, 1 - console, 2 - chat, 3 - both
is 1 (console) instead of 2 (chat)

**Comment by owwo** [comment]
thanks, I configured here is: 
// Enable or disable announcements when a CT attacks a non-rebelling T: 0 - disable, 1 - enable

**Comment by dataviruset** [comment]
Hi, thanks for your contributions, these have already been implemented in another pull request (#9). Closing this pull request.

**Pull request closed without merging**
