### PR TITLE
New noscope method

### PR DESCRIPTION
**Pull request by ghost**
Removed old code and replaced with a new code (that prevent quick scope)

### CODE REVIEW

**Comment by DorCoMaNdO** [comment]
I think that the FOV fix should be added back just in-case, to fix possible issues.

**Comment by Bara20** [comment]
All FOV change are now outside from LR_NoScope.

**Comment by data-bomb** [comment]
Is it okay to use FindSendPropOffs in a PreThink hook?  It will get called often.  Will this method work on CS:S as well?

**Comment by Bara20** [comment]
I see no problems with css (but not tested). And yes, not the best solutions with OnPreThink, but avoid noscope glitch.

**Comment by data-bomb** [comment]
Does this make it so that they can't zoom for 9999 ticks?  Would that last 78 seconds on a 128 tick server?  I'm not sure the math works that way but if so then we can save a lot of efficiency by setting this in InitializeLR and killing them after 78 seconds.

**Comment by Bara20** [comment]
After zoom or shooting,  is this timer closed then you can scope again. That's a reason why PreThink.

**Comment by data-bomb** [comment]
https://github.com/dataviruset/sm-hosties/commit/e608d2033848b0960beb334b11293ea1e9ea3d8d proposes the method discussed in the comments earlier to avoid the PreThink method while retaining current checks.

**Pull request closed without merging**
