### PR TITLE
Add travis support

### PR DESCRIPTION
**Pull request by Bara20**
New format to README.md (ex. README.txt)
Add changes from #12

### CODE REVIEW

**Comment by data-bomb** [comment]
I'm not sure what the advantage is of the readme in md format because we don't make use of any of the features yet, but travis support for automatic building is useful.

**Comment by Bara20** [comment]
Txt format doesn't work with build image and link. 

Can you replace in README.md Bara20 with dataviruset in build status link?

**Comment by data-bomb** [comment]
Ok, https://github.com/dataviruset/sm-hosties/commit/4c37e03b0a934cceead5f464946970a84f17ddce changes the link.  But now the link doesn't work.  Does dataviruset need to set something up?  I thought it was going to be automated without sharing.

**Comment by Bara20** [comment]
@dataviruset must actived this on travis-ci.org :/

**Comment by dataviruset** [comment]
I think it should be enabled now :)

**Pull request merged**
