### PR TITLE
Timer_Beacon

### PR DESCRIPTION
**Pull request by mrkos9i4ok**

### CODE REVIEW

**Comment by Bara20** [comment]
And that should work?

**Comment by mrkos9i4ok** [comment]
It works for me, well, about Help Beams I do not know what to do.

**Comment by mrkos9i4ok** [comment]
Yes, everything works at the moment)

**Comment by data-bomb** [comment]
@mrkos9i4ok , you have already done a great job and identified the problem with the Beacons.  It is that the modulus lines are not working any longer.  The only change we have made to that is 'new' to 'int', so if it is no longer working then this could be a larger issue with the SourceMod compiler.  Rather than re-invent the wheel, why not print out the values of modTime and iTimerCount and the modulus operation result?  If there is a compiler issue than this needs to be addressed.

**Comment by data-bomb** [comment]
int result iTimerCount %modTime;
PrintToConsole(LR_Player_Guard, "iTimerCount %d, modTime %d, result %d", iTimerCount, modTime, iTimerCount);
@mrkos9i4ok Are you availableto help investigate the root cause?

**Comment by mrkos9i4ok** [comment]
Yes,okey

**Comment by mrkos9i4ok** [comment]
iTimerCount 2, modTime 10, result 2
Always

**Comment by mrkos9i4ok** [comment]
int iTimerCount = 1;
iTimerCount++;
result iTiMerCount =2
Next step
int iTimerCount = 1;
iTimerCount++;
result iTiMerCount =2

**Comment by data-bomb** [comment]
@mrkos9i4ok Thanks! @Bara20 Looks like when we ported syntax we changed a static int declaration to just an int declaration.  This would definitely cause it to be 2 every time the timer triggers.  The fix should just be to change the initiation from
int iTimerCount = 1;
back to
static iTimerCount = 1;

Or is static variables no longer supported?  If this is the case, we should just switch to a global variable.

**Comment by data-bomb** [comment]
https://github.com/dataviruset/sm-hosties/commit/e083d33074f28d5efbe3677871a0fa23415219c5 seeks to address this.  This has caused the conflict for this section of the code.

**Comment by mrkos9i4ok** [comment]
Yes,All nice worked

**Comment by data-bomb** [comment]
Great! I will close this PR and my commit plus Bara's PR #86 will resolve this.

**Pull request closed without merging**
