### PR TITLE
Workaround for csgo with weapon_usp

### PR DESCRIPTION
**Pull request by Bara20**
I don't know why all lines was changed oO

### CODE REVIEW

**Comment by dataviruset** [comment]
Hi @Bara20, thanks for your contributions, I will look them through in the days. An obvious issue is all of those line changes, perhaps you can look into why they changed? If you're using the GitHub online editor I would recommend that you use another editor instead, because I suspect that there are something in the line endings or some unicode characters that you removed when you edited the files. These unicode characters should of course be dealt with, but let's do that separately and not as part of these pull requests. Let me know what you think. Thanks!

**Comment by Bara20** [comment]
I can make a new pull request with all changes or is separately better?

**Comment by dataviruset** [comment]
I think it's better to make a completely new pull request if possible, because then we won't have any commits changing this many lines in the git history. :)

**Comment by Bara20** [comment]
I'll make a new pull request today (or tomorrow) with all changes.

**Pull request closed without merging**
