### PR TITLE
Usage of multicolors

### PR DESCRIPTION
**Pull request by ghost**
More support for chat colors in css/csgo

### CODE REVIEW

**Comment by Bara20** [comment]
@DorCoMaNdO ?

**Comment by data-bomb** [comment]
I only think this is good if we come up with a color scheme in the translations file for how we're going to color in CS:S and CS:GO.  It could look much better with the colors but it's quite a bit of work, limited benefit, and prone to error.

**Comment by Bara20** [comment]
done for english translations

**Comment by data-bomb** [comment]
I will let @dataviruset weigh in on this.  It is a lot of changes but the players now would appear in a different color.  The color scheme could use improvement.  I would suggest we consider adding this to the dev branch once we fix all the important CS:GO bugs.

**Comment by dataviruset** [comment]
I'd say this is a bit of a bonus feature, I think we should wait until more important things are fixed, especially since this pull request has merge conflicts already :sob:

**Comment by Bara20** [comment]
btw. this is a csgo fix ( https://wiki.alliedmods.net/Csgo_quirks#Denoting_Text-Colors )

**Comment by data-bomb** [comment]
Unfortunately we can't edit this since it's 'ghost' and 'unknown repository' so we'll have to close this pull request with the possibility of adding this in a new pull request which is able to be merged into the beta branch.

**Pull request closed without merging**
