### PR TITLE
Mini fix KillAndReward LR and remove armor

### PR DESCRIPTION
**Pull request by Graffiti007**
Fix sm_hosties_lr_victorpoints on CSGO

### CODE REVIEW

**Comment by DorCoMaNdO** [comment]
Nice spot, but I don't believe that's the proper solution, I remember why we disabled that in CSGO and we planned to fix it, back in CSGO Beta days it used to crash the server, that was obvious fixed since, but we planned on increasing the score and not the frags in CSGO, in CS:S the only option was frags.

**Comment by Graffiti007** [comment]
Frags working on CSGO

**Comment by DorCoMaNdO** [comment]
I know they are, but they're not the representing what we intended them too, in CS:S there was no other option, in CSGO there is an actual score, when we initially updated SM_Hosties for CSGO we planned to use the score value and not the frags.

**Comment by data-bomb** [comment]
Superseded by #29

**Pull request closed without merging**
