### PR TITLE
Fix a lot of old stuff

### PR DESCRIPTION
**Pull request by Bara20**
Replaced old, unsupported and/or deprecated stuff with new stuff.

#1 #2 #3 #4 #5 #6 #7

@dataviruset

### CODE REVIEW

**Comment by DorCoMaNdO** [comment]
Please revert the workaround for the USP in CS:GO, your current code is only viable for the CT side and covers only the USP while there are other weapons causing issues.
I have a code I made a while ago for a private project of mine, I'll make some adjustments and submit it when I get some time to work on it.

**Comment by Bara20** [comment]
I know, but all reported crash bugs are with this reason. So I think this enough.

**Comment by dataviruset** [comment]
Maybe I should've mentioned it before, but it would be great if you could split everything up into many commits, one for every feature or small adjustment, instead of having one commit for a lot of things. That way it's easier to track what changed and which code changes are connected to each other. If you think it will be too much hassle, we can accept it like this for this time, though.

**Comment by Bara20** [comment]
@dataviruset Ok.

@DorCoMaNdO btw. We can add this nowm because it's only an workaround. You can change it at any time.

**Comment by dataviruset** [comment]
I know that @DorCoMaNdO might disagree, but I think @Bara20's fix is good enough for now, we can always make it better later :)

**Comment by owwo** [comment]
GetClientAuthId may not work at SM 1.5.0

**Comment by Bara20** [comment]
And? SM1.5 and SM1.6 are old stable and unsupported. Current stable release is 1.7.2 ( https://wiki.alliedmods.net/SourceMod_1.7.2_Release_Notes ), so why supported sm1.6 and/or lower?
Here is a list of supported versions: http://www.sourcemod.net/snapshots.php

**Comment by owwo** [comment]
I see the introduction, this plugin is Requirements: SourceMod 1.5.0+

'void' is not a Pawn type.

**Comment by Bara20** [comment]
https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax

I'll change the requirements.

**Comment by owwo** [comment]
:3 I think it is better supported SM 1.5.0.

**Comment by Bara20** [comment]
No, sourcemod 1.5 is a unsupported version (https://github.com/alliedmodders/sourcemod/tree/1.5-dev last commit 2014...) and sourcemod 1.6 (https://github.com/alliedmodders/sourcemod/tree/1.6-dev last commit february 2015...).

**Comment by owwo** [comment]
Ah, You're right.

**Comment by Bara20** [comment]
? 
@dataviruset

**Pull request merged**
